### ISSUE TITLE
modify antd theme cant work

### ISSUE THREAD

**Issue by wason001** [xyy94813/customize-cra-less-loader#3]
addLessLoader({
      lessLoaderOptions: {
        lessOptions: {
          javascriptEnabled: true,
          modifyVars: {
            'primary-color': 'rgb(192, 208, 157)',
            'link-color': 'rgb(192, 208, 157)'
          }
        }
      }
    })

**Comment by xyy94813** [comment]
I try it in my project.

The variables of less in project `src` dir is working well, but the variables of less in `node_modules` is not working.

```js
// conf.js
//...
addLessLoader({
        cssLoaderOptions: {
          modules: {
            localIdentName,
          },
        },
        lessLoaderOptions: {
          lessOptions: {
            javascriptEnabled: true,
            modifyVars: {
              'primary-color': 'green',
            },
          },
        },
      })
//...
```

```less
// component.module.less
@import '~antd/es/style/themes/default.less';

.container {
    background: @primary-color;
  }
```

variables in `component.module.less` will be override.
